### ISSUE TITLE
Add install guide to git main readme

### ISSUE THREAD

**Issue by enfJoao** [2sic/app-tutorial-pdf#1]
These instructions are in the app template:
```
Copy Puppeteer binaries from /App-Print/Setup_Files/Puppeteer_Binaries to the "/bin" directory of your DNN project root. (Try refreshing to make sure the Puppeteer warning is gone.)
Copy the Print-App Skin from /App-Print/Setup_Files/Print_Skin to the "/Portals/_default/Skins" of your DNN project directory.
```

However, to see the app you already need these files in place, else the template will output the missing directives error.
Please add these instructions to the main git readme.

**Comment by iJungleboy** [comment]
@maaaximum-at-2sic  could you check / improve?

**Comment by maaaximum-at-2sic** [comment]
Thank you for reporting this issue 😄 . 

The instructions will remain in the app.
We've improved the error handling for the tutorial view, so the app won't throw missing dll exceptions anymore.

You can find the updated version [here](https://github.com/2sic/app-tutorial-pdf/releases/tag/v01.00.01).
